name: "Update BitBake Recipe"
description: "Automatically update a BitBake recipe in a Yocto meta repository based on a Rust project."
inputs:
  git_token:
    description: "Git Token with write permissions to the Yocto meta repository."
    required: true
  yocto_repository:
    description: "The name of the Yocto meta repository within the configured organization."
    required: true
  yocto_branch:
    description: "The branch of the Yocto meta repository to update."
    required: true
  organization:
    description: "The organization of the Yocto meta repository."
    required: true
  recipe_path:
    description: "The path to the folder in the Yocto meta repository where the recipe is located."
    required: true
  author:
    description: "The author of the pull request."
    required: true
  committer:
    description: "The committer of the pull request."
    required: true
  method:
    description: "The method to use for updating the BitBake recipe: 'cargo-bitbake' or 'meta-rust-bin'."
    default: "meta-rust-bin"
    required: false
runs:
  using: "composite"
  steps:
    # Check out the application code.
    - name: Checkout Application
      uses: actions/checkout@v3

    # Set up the Rust toolchain.
    - name: Setup Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    
    # Extract the package info.
    - name: Extract package name and title from Cargo.toml
      run: |
        package_name=$(cargo read-manifest | jq -r .name)
        package_version=$(cargo read-manifest | jq -r .version)
        
        if [ -z "$package_name" ] || [ -z "$package_version" ]; then
          echo "Error: Could not extract package info from Cargo.toml" >&2
          exit 1
        fi
        
        package_title=$(echo "$package_name" | tr '-' ' ' | awk '{for (i=1;i<=NF;i++) { $i=toupper(substr($i,1,1)) substr($i,2) } print}')
        
        echo "PACKAGE_NAME=$package_name" >> $GITHUB_ENV
        echo "PACKAGE_TITLE=$package_title" >> $GITHUB_ENV
        echo "PACKAGE_VERSION=$package_version" >> $GITHUB_ENV
      shell: sh

    # Generate the BitBake file using cargo bitbake.
    - name: Generate BitBake file
      if: inputs.method == 'cargo-bitbake'
      run: |
        cargo install --locked cargo-bitbake
        cargo bitbake
      shell: sh

    - name: Generate BitBake file
      if: inputs.method == 'meta-rust-bin'
      run: |
        cat > ${{ env.PACKAGE_NAME }}_${{ env.PACKAGE_VERSION }}.bb <<-EOF
          inherit cargo_bin

          do_compile[network] = "1"

          SRC_URI += "git://github.com/${{ github.repository }}.git;protocol=https;nobranch=1;branch=${{ github.base_ref }}"
          SRCREV = "${{ github.sha }}"
          S = "\${WORKDIR}/git"
          CARGO_HOME = "\${S}/.cargo"
          LICENSE="CLOSED"

          include ${{ env.PACKAGE_NAME }}.inc
        EOF
      shell: sh

    # Check out the Yocto meta repository.
    - name: Checkout Yocto Meta Repo
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.organization }}/${{ inputs.yocto_repository }}
        token: ${{ inputs.git_token }}
        path: ${{ inputs.yocto_repository }}

    # Copy the generated BitBake file into the desired recipe folder.
    - name: Copy generated BitBake file to recipe
      run: |
        rm -f ${{ inputs.yocto_repository }}/${{ inputs.recipe_path }}/${{ env.PACKAGE_NAME }}/*.bb
        cp *.bb ${{ inputs.yocto_repository }}/${{ inputs.recipe_path }}/${{ env.PACKAGE_NAME }}/
      shell: sh

    # Create a pull request with the updated recipe.
    - name: Create Pull Request for Updated Recipe
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ inputs.git_token }}
        commit-message: "fix(${{ env.PACKAGE_NAME }}): update to ${{ env.PACKAGE_VERSION }}"
        branch: update-${{ env.PACKAGE_NAME }}-bitbake-recipe-${{ env.PACKAGE_VERSION }}
        title: "Update ${{ env.PACKAGE_TITLE }} BitBake recipe for release ${{ env.PACKAGE_VERSION }}"
        body: "Automatically generated update for ${{ env.PACKAGE_TITLE }} BitBake recipe based on release ${{ env.PACKAGE_VERSION }}."
        base: ${{ inputs.yocto_branch }}
        path: ${{ inputs.yocto_repository }}
        committer: ${{ inputs.committer }}
        author: ${{ inputs.author }}
